version: '3'
services:
  app:
    build: .
    ports:
      - 80:80
    volumes:
      - ./src/:/var/www/html/
      - ./config/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    command: /usr/sbin/apache2ctl -D FOREGROUND & tail -f /var/log/apache2/error.log
  db:
    image: mysql:8.0.33
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 10
    