version: '3'
services:
  app:
    image: php:7.4-apache
    ports:
      - 8000:80
    volumes:
      - ./src:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
  db:
    image: mysql:8.0.33
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 10
    